sudo: required

dist: trusty

language: python

python:
    - "3.6"


install:
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    # Install dependencies
    - conda env update -f environment.yml
    - source activate test-env


script:
    - python $TRAVIS_BUILD_DIR/.tests/nbrun.py

notifications:
  email: false
